#!/bin/bash
#Date:2015-6-25
#Auther:Yrd
#Description:Display the AscII table.

seq 0 1 127 | awk '{printf("\x%02x",$1)}'|awk '{print "\""$1"\""}'|xargs echo -en | od -Ax -tx1ac | grep -A3 --color=always '^[0-9]\{6,\}.*$'

